use std::{time::Duration, borrow::Cow};
use autometrics::prometheus_exporter;
use axum::{Router, routing::get};
use opentelemetry::KeyValue;
use opentelemetry_otlp::{new_pipeline, new_exporter, WithExportConfig, Protocol};
use opentelemetry_sdk::{runtime, Resource};
use opentelemetry_semantic_conventions::resource;
use tokio::spawn;
use tracing_subscriber::{prelude::__tracing_subscriber_SubscriberExt, util::SubscriberInitExt};
use crate::{config::CONFIG, utils};
use opentelemetry_sdk::trace;

pub struct OpentelemetryAdapter { }

impl OpentelemetryAdapter {

  // initTraceExporter creates a trace-exporter which takes all the spans generated by the
  // OpenTelemetry SDK and batch exports them to a Jaeger collector.
  pub fn initTraceExporter( ) {
    let traceExporter= new_exporter( )
      .tonic( )
      .with_endpoint(&*CONFIG.JAEGER_COLLECTOR_URL)
      .with_protocol(Protocol::Grpc)
      .with_timeout(Duration::from_secs(3));

    let tracer= new_pipeline( )
      .tracing( )
      .with_exporter(traceExporter)
      .with_trace_config(
        trace::Config {
          resource: Cow::Owned(Resource::new(vec!{
            KeyValue::new(resource::SERVICE_NAME, "authentication-service")
          })),

          ..Default::default( )
        }
      )
      .install_batch(runtime::Tokio) // Batch export spans.
      .expect("Error creating tracer provider");

    // Spans captured by the 'tracing' crate, will be passed on to the above OpenTelemetry tracer.
    // That tracer will then send the spans to the Jaeger collector.
    tracing_subscriber::registry( )
      .with(tracing_opentelemetry::layer( ).with_tracer(tracer))
      .try_init( )
      .expect("Error initiliazing tracing-subscriber for OpenTelemetry");

    tracing::info!("Created OpenTelemetry tracer and trace exporter successfully");
  }

  // initMetricsExporter
  pub fn initMetricsExporter( ) {
    prometheus_exporter::init( );

    let threadCancellationToken= utils::THREAD_CANCELLATION_TOKEN.clone( );
    spawn(async move {
      let address= format!("[::]:{}", &*CONFIG.METRICS_SERVER_PORT);
      let address= address.parse( )
                          .expect(&format!("Error parsing address where metrics will be published : {}", address));

      let router= Router::new( )
        .route("/metrics", get(| | async { prometheus_exporter::encode_http_response( ) }));

      tracing::info!("Starting metrics server");

      axum::Server::bind(&address)
        .serve(router.into_make_service( ))
        .with_graceful_shutdown(threadCancellationToken.cancelled( ))
        .await
        .expect("Error starting HTTP metrics server");
    });
  }
}